// Generated by CoffeeScript 1.6.1
(function() {

  this.PhoneListController = [
    '$scope', '$http', function($scope, $http) {
      var _this = this;
      $scope.query = '';
      $scope.order = 'age';
      $http.post('http://localhost:8000/phones/get_phones').success(function(data) {
        if (data.success) {
          return $scope.phones = data.phones;
        }
      });
      return $scope.has_query = function(query) {
        if (query.trim().length > 0) {
          return true;
        } else {
          return false;
        }
      };
    }
  ];

  this.PhoneDetailController = [
    '$scope', '$routeParams', '$http', function($scope, $route_params, $http) {
      $scope.phone_id = $route_params.phone_id;
      return $http.post("http://localhost:8000/phones/get_phone_details?phone_id=" + $scope.phone_id).success(function(data) {
        if (data.success) {
          $scope.phone_details = data.details;
          return $scope.main_image = data.details.images[0];
        }
      }, $scope.set_image = function(img) {
        return $scope.main_image = img;
      });
    }
  ];

}).call(this);
